### ISSUE TITLE
Official support

### ISSUE THREAD

**Issue by topjohnwu** [Magisk-Modules-Repo/magisk-soundmod-s7-dual-l3#1]
Hello, @djb77 
You ported a popular sound mod for the S7, which is a great job. I wonder if the original developer is acknowledged and allow this port. Also, it would also be nice if he/she would love to officially support this version, or you being the official Magisk version maintainer which will update the module in a timely manner.

**Comment by djb77** [comment]
Hey John :)

The dev is completely aware that I did this module, and I have his 
permission to do so also.
As far as support goes, I'm guessing that I'm taking care of the magisk 
side of it, the dev didn't say any different.
Ofcourse I will be keeping the module up-to-date as much as possible, 
whether it be updates on the mod itself or your template. The good thing 
is that the mod hasn't changed for a while now, so its a safe bet to say 
it will be a final.

All the best.
Dwayne (djb77)

**Comment by topjohnwu** [comment]
Cool, thanks for clarifying!
